### ISSUE TITLE
Fehlende Ruf-Waren bei Schlachtfeldhändlern

### ISSUE THREAD

**Issue by SimonMallow** [HateForge-WoW/Bugtracker#60]
Bei den beiden Händlern der Schlachtfelder für Alterac Valley  und Warsong verkaufen die Händler keine oder zu wenige Waren für Ruf. Ganz anders sieht es bei dem Arathibecken aus, dort sind alle Waren für Ruf erhältlich.

1. Gehe zu Illiyana Moonblaze und Thanthaldis Snowgleam
2. Klicke auf die Händler
3. Fehlende oder keine Waren

Es sollten eigentlich alle Rufwaren angezeigt werden.

![Keine Waren](https://github.com/HateForge-WoW/Bugtracker/assets/143521488/eb01f345-d303-41d5-990a-76bec9aaf0ae)
![keine Waren2](https://github.com/HateForge-WoW/Bugtracker/assets/143521488/9163ad6c-0c15-4ed3-8b9c-8ebb29a0cf70)

**Comment by schell244** [comment]
Es scheint so, als wäre dies expected behavior, da die items keine ruf anforderungen haben (siehe wowhead) uns stattdessen eine condition beim vendor verwedet wird. Finde es aber auch komisch, es nicht konsistent zu handhaben. Ist nun "gefixed" (also die items haben nun ruf requirements und es gibt keine vendor condition mehr. Danke dür den Report!
